Update QAT workflow to use PR comments (#46)
* Trying out not failing QAT action if QAT checks fail but instead warn.

* rearrange commands

* Try hijacking the exit code

* comment out continue-on-error

* Add notice

* try PR comment

* comment

* allow write perms

* test PR permissions

* cleanup

* Add report status icon

* broken emoji?

* fix operator

* bugfix

* try a different flag approach

* make checkly status an output

* Improve some of the language

* conditional language

* remove empty line

* cleanup some comments

* Use new environment variables for output

* If github.event.action == 'ready_for_review'

* Testing out some new conditions.

* adjust conditional to always run job if in draft mode.

* Fix reference error

* testing output

* testing string output

* fix the boolean

* bugfix

* Only update the checkly report if it differs from the first run.

* Only check the summary

* dont need to watch for draft anymore

* use single or double quotes instead of template literals

* New delete old comment approach

* comment cleanup

* remove draft conditional now that we cleaned up the output

diff --git a/.github/workflows/qat.yml b/.github/workflows/qat.yml
--- a/.github/workflows/qat.yml
+++ b/.github/workflows/qat.yml
@@ -26,6 +26,8 @@ on:
 
 permissions:
   contents: read
+  # To allow action to post to PR.
+  pull-requests: write
 
 # See https://www.checklyhq.com/docs/cli/command-line-reference/#npx-checkly-deploy and supporting documentation for
 # more details on Checkly environment variables.
@@ -92,7 +94,6 @@ jobs:
     # if the check_files step in the check-qat job doesn't fail
     needs:
       - check-qat
-    if: needs.check-qat.outputs.status == 'true'
 
     concurrency:
       group: ${{ github.ref_name || github.run_id }}-checkly-qat
@@ -118,10 +119,55 @@ jobs:
         id: run-checks
         if: github.ref != 'refs/heads/main' # We don't want to run checks on main branch pushes
         run: |
+          set +e # Disable exit on error
           npx checkly test --config=$(find . -name checkly.config.ts) -e ENVIRONMENT_URL=https://${{ env.FEATURE_BRANCH_NAME }}.${{ inputs.QA_SITE_DOMAIN }} --reporter=github --record
+          exit_code=$?
+          set -e # Enable exit on error
+          if [ $exit_code -ne 0 ]; then
+            echo "::error::Checkly checks failed. Please check the checkly-github-report.md in the summary for more details."
+            echo "checkly_failed=true" >> $GITHUB_OUTPUT
+          else
+            echo "::notice::Checkly checks Passed! Please check the checkly-github-report.md in the summary for more details."
+            echo "checkly_failed=false" >> $GITHUB_OUTPUT
+          fi
           cat checkly-github-report.md > $GITHUB_STEP_SUMMARY
       - name: Deploy checks # Deploy checks to Checkly for debugging
         # Only run if the pull request is merging into the main branch
         if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
         id: deploy-checks
         run: npx checkly deploy --config=$(find . -name checkly.config.ts) --force
+      - name: Add Checkly report comment to PR
+        uses: actions/github-script@v6
+        if: github.event_name == 'pull_request'
+        with:
+          github-token: ${{ secrets.GITHUB_TOKEN }}
+          script: |
+            const fs = require('fs');
+            const report = fs.readFileSync('checkly-github-report.md', 'utf8');
+            const checklyFailed = ${{ steps.run-checks.outputs.checkly_failed }};
+            const checklyStatus = checklyFailed ? ':x: Some Playwright tests failed. Please review the Checkly Report to verify no breaking changes were introduced' : ':white_check_mark: All Playwright tests passed. Checkly Report';
+
+            const existingComment = await github.rest.issues.listComments({
+              issue_number: context.issue.number,
+              owner: context.repo.owner,
+              repo: context.repo.repo
+            });
+
+            // Delete any existing Checkly Report comments
+            for (const comment of existingComment.data) {
+              if (comment.body.includes('Checkly Report')) {
+                await github.rest.issues.deleteComment({
+                  owner: context.repo.owner,
+                  repo: context.repo.repo,
+                  comment_id: comment.id
+                });
+              }
+            };
+
+            // Create a new Checkly Report comment
+            github.rest.issues.createComment({
+              issue_number: context.issue.number,
+              owner: context.repo.owner,
+              repo: context.repo.repo,
+              body: `<details><summary>${checklyStatus}:</summary>\n\n${report}</details>`
+            });
